### PR TITLE
✨ Add `Value` helpers and trait impls

### PR DESCRIPTION
**Pull request by CosmicHorrorDev**
Stemming from https://github.com/zeenix/tomling/pull/23#issue-2703532905

Adds (eliding lifetimes for brevity)

- `Value::as_str(&self) -> Option<&str>`
- `Value::as_i64(&self) -> Option<i64>`
- `Value::as_f64(&self) -> Option<f64>`
- `Value::as_bool(&self) -> Option<bool>`
- `Value::as_array(&self) -> Option<&Array>`
- `Value::as_table(&self) -> Option<&Table>`
- `impl From<X> for Value`
  - `String`
  - `&str`
  - `Cow<str>`
  - `i64`
  - `f64`
  - `bool`
  - `Array`
  - `Table`
- `impl<V: Into<Value>> FromIterator<V> for Value` (arrays)
- `impl<K: Into<Cow<str>>, V: Into<Value>> FromIterator<(K, V)> for Value` (tables)

There's a decent loc reduction, but also significant line-noise reduction in the tests that were manually constructing `Value`s

---

I briefly started adding `PartialEq<T>` impls for `Value`, but then I quickly realized just how many different combinations would be required to cover all the common cases, and instead I noped out and leaned into the conversion helpers more

### CODE REVIEW

**Comment by zeenix** [comment]
> * `Value::as_str(&self) -> Option<&str>`
> * `Value::as_i64(&self) -> Option<i64>`
> * `Value::as_f64(&self) -> Option<f64>`
> * `Value::as_bool(&self) -> Option<bool>`
> * `Value::as_array(&self) -> Option<&Array>`
> * `Value::as_table(&self) -> Option<&Table>`

Out of coincidence, I also added conversions in [my WIP branch](https://github.com/zeenix/tomling/commits/workspace-deps/) but I went for [`Tryfrom` impls instead](https://github.com/zeenix/tomling/blob/2bd90cb0c852555b8647dff164412d58ec8bd92a/src/value.rs#L42) and also used a macro to reduce the LOC. I think I prefer my approach this really is a conversion and `*From` impls are meant for that. Moreover, that enables generic code like I'm trying to [add in the same commit](https://github.com/zeenix/tomling/blob/2bd90cb0c852555b8647dff164412d58ec8bd92a/src/cargo/package.rs#L191).

I'll split the conversions into a separate PR soon so you can rebase on top of that. I really should have done that already but I didn't know that I'll hit a wall with a lifetime issue (try building that branch if you're curious).

**Comment by CosmicHorrorDev** [comment]
> I think I prefer my approach this really is a conversion and *From impls are meant for that. Moreover, that enables generic code like I'm trying to add in the same commit.

We can do both if you want, but my code is following the general [ad-hoc conversions](https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv) which is still certainly idiomatic rust (and also mimics the APIs you see in `serde_json`, `toml`, etc.)

The main reason I don't want to drop the `.as_*()` helpers is that you can't turbofish `.try_into()` so a lot of the method-chainy code gets a lot messier without it

**Comment by zeenix** [comment]
> my code is following the general [ad-hoc conversions](https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv) which is still certainly idiomatic rust

That guideline is about naming of such conversion methods and doesn't say anything about preferring these methods over implementing the conversion traits.

> (and also mimics the APIs you see in `serde_json`, `toml`, etc.)

That's a good argument though. :)

> We can do both if you want, 

Yeah, sure. Let's do that. :) Should I merge then or you want to review the changes?

**Comment by CosmicHorrorDev** [comment]
You can take over this PR. I don't think I'll have enough spare time to be able to contribute here more

**Comment by zeenix** [comment]
>  I don't think I'll have enough spare time to be able to contribute here more

I hope everything is ok? It's very sad and surprising to hear, given that I've changed the main goals of the project twice already, based on your promise to help develop and maintain this crate and now you'll be disappearing completely so soon. 😔

**Comment by CosmicHorrorDev** [comment]
Eh it's just life deciding to be busy again, so I won't have much free time to dedicate to OSS for the next few months at least unfortunately

All of my other projects are in a pretty stable state, but this one being new means it would demand a lot more attention than I'll be able to give

**Comment by zeenix** [comment]
> Eh it's just life deciding to be busy again, so I won't have much free time to dedicate to OSS for the next few months at least unfortunately

Ah ok. I appreciate you being so honest about it. Most folks keep promising to finish their PRs but never do. :(

**Comment by zeenix** [comment]
> You can take over this PR.

Done. Thanks.

**Pull request merged**
