### PR TITLE
✅ Wire up `toml-test-harness` test suite

### LINKED ISSUE #6: Consider testing parser against toml-test
TOML maintains [`toml-test`](https://github.com/toml-lang/toml-test), a suite of tests meant to test TOML parsers, and there are rust-specific helpers like [`toml-test-harness`](https://crates.io/crates/toml-test-harness). I would highly recommend testing against the official suite as it covers some of the tricker parts to get right like when it's valid to append to tables

### PR DESCRIPTION
**Pull request by CosmicHorrorDev**
Resolves #6

Wires up the test suite and ignores all of the tests that aren't currently passing (although it looks like there's some low-hanging fruit)

### CODE REVIEW

**Comment by CosmicHorrorDev** [comment]
There are currently 343 passing, 210 failing, and 11 ignored from the TOML `1.0.0` suite

<details>

<summary>Failing tests</summary>

- [ ] [`valid/empty-file.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/empty-file.toml)
- [ ] [`valid/example.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/example.toml)
- [ ] [`valid/spec-example-1-compact.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec-example-1-compact.toml)
- [ ] [`valid/spec-example-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec-example-1.toml)
- [ ] [`valid/array/array.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/array/array.toml)
- [ ] [`valid/array/array-subtables.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/array/array-subtables.toml)
- [ ] [`valid/array/mixed-string-table.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/array/mixed-string-table.toml)
- [ ] [`valid/array/string-quote-comma-2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/array/string-quote-comma-2.toml)
- [ ] [`valid/array/string-quote-comma.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/array/string-quote-comma.toml)
- [ ] [`valid/array/string-with-comma-2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/array/string-with-comma-2.toml)
- [ ] [`valid/array/string-with-comma.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/array/string-with-comma.toml)
- [ ] [`valid/array/table-array-string-backslash.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/array/table-array-string-backslash.toml)
- [ ] [`valid/comment/after-literal-no-ws.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/comment/after-literal-no-ws.toml)
- [ ] [`valid/array/open-parent-table.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/array/open-parent-table.toml)
- [ ] [`valid/array/nested-double.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/array/nested-double.toml)
- [ ] [`valid/comment/noeol.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/comment/noeol.toml)
- [ ] [`valid/datetime/datetime.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/datetime/datetime.toml)
- [ ] [`valid/datetime/edge.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/datetime/edge.toml)
- [ ] [`valid/datetime/leap-year.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/datetime/leap-year.toml)
- [ ] [`valid/datetime/local-time.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/datetime/local-time.toml)
- [ ] [`valid/datetime/local-date.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/datetime/local-date.toml)
- [ ] [`valid/datetime/local.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/datetime/local.toml)
- [ ] [`valid/datetime/milliseconds.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/datetime/milliseconds.toml)
- [ ] [`valid/datetime/timezone.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/datetime/timezone.toml)
- [ ] [`valid/float/exponent.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/float/exponent.toml)
- [ ] [`valid/float/float.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/float/float.toml)
- [ ] [`valid/float/inf-and-nan.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/float/inf-and-nan.toml)
- [ ] [`valid/float/max-int.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/float/max-int.toml)
- [ ] [`valid/float/long.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/float/long.toml)
- [ ] [`valid/float/underscore.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/float/underscore.toml)
- [ ] [`valid/float/zero.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/float/zero.toml)
- [ ] [`valid/comment/tricky.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/comment/tricky.toml)
- [ ] [`valid/comment/everywhere.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/comment/everywhere.toml)
- [ ] [`valid/inline-table/empty.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/inline-table/empty.toml)
- [ ] [`valid/inline-table/key-dotted-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/inline-table/key-dotted-1.toml)
- [ ] [`valid/inline-table/key-dotted-2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/inline-table/key-dotted-2.toml)
- [ ] [`valid/inline-table/key-dotted-3.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/inline-table/key-dotted-3.toml)
- [ ] [`valid/inline-table/key-dotted-4.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/inline-table/key-dotted-4.toml)
- [ ] [`valid/inline-table/key-dotted-5.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/inline-table/key-dotted-5.toml)
- [ ] [`valid/inline-table/key-dotted-6.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/inline-table/key-dotted-6.toml)
- [ ] [`valid/inline-table/key-dotted-7.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/inline-table/key-dotted-7.toml)
- [ ] [`valid/integer/float64-max.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/integer/float64-max.toml)
- [ ] [`valid/integer/integer.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/integer/integer.toml)
- [ ] [`valid/integer/literals.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/integer/literals.toml)
- [ ] [`valid/integer/underscore.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/integer/underscore.toml)
- [ ] [`valid/integer/long.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/integer/long.toml)
- [ ] [`valid/integer/zero.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/integer/zero.toml)
- [ ] [`valid/key/escapes.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/key/escapes.toml)
- [ ] [`valid/key/space.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/key/space.toml)
- [ ] [`valid/key/quoted-unicode.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/key/quoted-unicode.toml)
- [ ] [`valid/spec/array-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/array-1.toml)
- [ ] [`valid/spec/float-0.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/float-0.toml)
- [ ] [`valid/spec/float-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/float-1.toml)
- [ ] [`valid/spec/float-2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/float-2.toml)
- [ ] [`valid/spec/inline-table-0.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/inline-table-0.toml)
- [ ] [`valid/spec/integer-0.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/integer-0.toml)
- [ ] [`valid/spec/integer-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/integer-1.toml)
- [ ] [`valid/spec/integer-2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/integer-2.toml)
- [ ] [`valid/spec/array-0.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/array-0.toml)
- [ ] [`valid/spec/array-of-tables-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/array-of-tables-1.toml)
- [ ] [`valid/spec/local-date-0.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/local-date-0.toml)
- [ ] [`valid/spec/offset-date-time-0.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/offset-date-time-0.toml)
- [ ] [`valid/spec/local-date-time-0.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/local-date-time-0.toml)
- [ ] [`valid/spec/local-time-0.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/local-time-0.toml)
- [ ] [`valid/spec/offset-date-time-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/offset-date-time-1.toml)
- [ ] [`valid/spec/string-0.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/string-0.toml)
- [ ] [`valid/spec/string-4.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/string-4.toml)
- [ ] [`valid/spec/table-0.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/table-0.toml)
- [ ] [`valid/spec/string-2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/string-2.toml)
- [ ] [`valid/spec/string-7.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/string-7.toml)
- [ ] [`valid/spec/string-3.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/string-3.toml)
- [ ] [`valid/spec/table-5.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/table-5.toml)
- [ ] [`valid/spec/table-6.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/table-6.toml)
- [ ] [`valid/spec/table-4.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/table-4.toml)
- [ ] [`valid/spec/table-7.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/table-7.toml)
- [ ] [`valid/string/double-quote-escape.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/string/double-quote-escape.toml)
- [ ] [`valid/string/escape-tricky.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/string/escape-tricky.toml)
- [ ] [`valid/spec/table-3.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec/table-3.toml)
- [ ] [`valid/string/ends-in-whitespace-escape.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/string/ends-in-whitespace-escape.toml)
- [ ] [`valid/string/escaped-escape.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/string/escaped-escape.toml)
- [ ] [`valid/string/escapes.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/string/escapes.toml)
- [ ] [`valid/string/multiline-quotes.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/string/multiline-quotes.toml)
- [ ] [`valid/string/multiline-escaped-crlf.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/string/multiline-escaped-crlf.toml)
- [ ] [`valid/string/multiline-empty.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/string/multiline-empty.toml)
- [ ] [`valid/string/raw-multiline.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/string/raw-multiline.toml)
- [ ] [`valid/string/nl.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/string/nl.toml)
- [ ] [`valid/string/quoted-unicode.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/string/quoted-unicode.toml)
- [ ] [`valid/string/multiline.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/string/multiline.toml)
- [ ] [`valid/table/array-implicit.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/table/array-implicit.toml)
- [ ] [`valid/string/start-mb.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/string/start-mb.toml)
- [ ] [`valid/table/array-implicit-and-explicit-after.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/table/array-implicit-and-explicit-after.toml)
- [ ] [`valid/table/empty.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/table/empty.toml)
- [ ] [`valid/table/array-within-dotted.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/table/array-within-dotted.toml)
- [ ] [`valid/table/keyword.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/table/keyword.toml)
- [ ] [`valid/string/unicode-escape.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/string/unicode-escape.toml)
- [ ] [`valid/table/no-eol.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/table/no-eol.toml)
- [ ] [`valid/table/whitespace.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/table/whitespace.toml)
- [ ] [`valid/table/array-nest.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/table/array-nest.toml)
- [ ] [`valid/table/without-super.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/table/without-super.toml)
- [ ] [`valid/table/names.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/table/names.toml)
- [ ] [`invalid/array/extend-defined-aot.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/array/extend-defined-aot.toml)
- [ ] [`invalid/array/extending-table.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/array/extending-table.toml)
- [ ] [`invalid/array/tables-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/array/tables-1.toml)
- [ ] [`invalid/control/bare-cr.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/bare-cr.toml)
- [ ] [`invalid/array/tables-2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/array/tables-2.toml)
- [ ] [`invalid/control/comment-cr.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/comment-cr.toml)
- [ ] [`invalid/control/comment-ff.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/comment-ff.toml)
- [ ] [`invalid/control/comment-del.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/comment-del.toml)
- [ ] [`invalid/control/comment-null.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/comment-null.toml)
- [ ] [`invalid/control/comment-lf.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/comment-lf.toml)
- [ ] [`invalid/control/comment-us.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/comment-us.toml)
- [ ] [`invalid/control/multi-cr.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/multi-cr.toml)
- [ ] [`invalid/control/multi-del.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/multi-del.toml)
- [ ] [`invalid/control/multi-lf.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/multi-lf.toml)
- [ ] [`invalid/control/multi-null.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/multi-null.toml)
- [ ] [`invalid/control/multi-us.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/multi-us.toml)
- [ ] [`invalid/control/rawmulti-del.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/rawmulti-del.toml)
- [ ] [`invalid/control/rawmulti-cd.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/rawmulti-cd.toml)
- [ ] [`invalid/control/rawmulti-lf.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/rawmulti-lf.toml)
- [ ] [`invalid/control/rawmulti-null.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/rawmulti-null.toml)
- [ ] [`invalid/control/rawmulti-us.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/rawmulti-us.toml)
- [ ] [`invalid/control/rawstring-cr.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/rawstring-cr.toml)
- [ ] [`invalid/control/rawstring-del.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/rawstring-del.toml)
- [ ] [`invalid/control/rawstring-lf.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/rawstring-lf.toml)
- [ ] [`invalid/control/rawstring-null.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/rawstring-null.toml)
- [ ] [`invalid/control/rawstring-us.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/rawstring-us.toml)
- [ ] [`invalid/control/string-bs.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/string-bs.toml)
- [ ] [`invalid/control/string-cr.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/string-cr.toml)
- [ ] [`invalid/control/string-del.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/string-del.toml)
- [ ] [`invalid/control/string-lf.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/string-lf.toml)
- [ ] [`invalid/control/string-null.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/string-null.toml)
- [ ] [`invalid/control/string-us.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/control/string-us.toml)
- [ ] [`invalid/float/leading-zero.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/float/leading-zero.toml)
- [ ] [`invalid/inline-table/duplicate-key-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/inline-table/duplicate-key-1.toml)
- [ ] [`invalid/inline-table/overwrite-02.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/inline-table/overwrite-02.toml)
- [ ] [`invalid/inline-table/overwrite-01.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/inline-table/overwrite-01.toml)
- [ ] [`invalid/inline-table/overwrite-03.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/inline-table/overwrite-03.toml)
- [ ] [`invalid/inline-table/overwrite-05.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/inline-table/overwrite-05.toml)
- [ ] [`invalid/inline-table/overwrite-04.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/inline-table/overwrite-04.toml)
- [ ] [`invalid/inline-table/overwrite-09.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/inline-table/overwrite-09.toml)
- [ ] [`invalid/integer/leading-zero-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/integer/leading-zero-1.toml)
- [ ] [`invalid/integer/leading-zero-2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/integer/leading-zero-2.toml)
- [ ] [`invalid/key/after-array.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/key/after-array.toml)
- [ ] [`invalid/key/after-table.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/key/after-table.toml)
- [ ] [`invalid/key/after-value.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/key/after-value.toml)
- [ ] [`invalid/key/dotted-redefine-table-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/key/dotted-redefine-table-1.toml)
- [ ] [`invalid/key/duplicate-keys-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/key/duplicate-keys-1.toml)
- [ ] [`invalid/key/dotted-redefine-table-2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/key/dotted-redefine-table-2.toml)
- [ ] [`invalid/key/duplicate-keys-3.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/key/duplicate-keys-3.toml)
- [ ] [`invalid/key/duplicate-keys-2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/key/duplicate-keys-2.toml)
- [ ] [`invalid/key/duplicate-keys-4.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/key/duplicate-keys-4.toml)
- [ ] [`invalid/key/newline-2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/key/newline-2.toml)
- [ ] [`invalid/key/newline-3.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/key/newline-3.toml)
- [ ] [`invalid/key/no-eol.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/key/no-eol.toml)
- [ ] [`invalid/key/special-character.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/key/special-character.toml)
- [ ] [`invalid/string/bad-byte-escape.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/bad-byte-escape.toml)
- [ ] [`invalid/spec/inline-table-3-0.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/spec/inline-table-3-0.toml)
- [ ] [`invalid/spec/inline-table-2-0.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/spec/inline-table-2-0.toml)
- [ ] [`invalid/string/bad-escape-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/bad-escape-1.toml)
- [ ] [`invalid/string/bad-escape-2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/bad-escape-2.toml)
- [ ] [`invalid/string/bad-escape-3.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/bad-escape-3.toml)
- [ ] [`invalid/string/bad-hex-esc-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/bad-hex-esc-1.toml)
- [ ] [`invalid/string/bad-hex-esc-2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/bad-hex-esc-2.toml)
- [ ] [`invalid/string/bad-hex-esc-3.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/bad-hex-esc-3.toml)
- [ ] [`invalid/string/bad-hex-esc-4.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/bad-hex-esc-4.toml)
- [ ] [`invalid/string/bad-hex-esc-5.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/bad-hex-esc-5.toml)
- [ ] [`invalid/string/bad-multiline.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/bad-multiline.toml)
- [ ] [`invalid/string/bad-slash-escape.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/bad-slash-escape.toml)
- [ ] [`invalid/spec/table-9-0.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/spec/table-9-0.toml)
- [ ] [`invalid/spec/table-9-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/spec/table-9-1.toml)
- [ ] [`invalid/string/bad-uni-esc-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/bad-uni-esc-1.toml)
- [ ] [`invalid/string/bad-uni-esc-2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/bad-uni-esc-2.toml)
- [ ] [`invalid/string/bad-uni-esc-3.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/bad-uni-esc-3.toml)
- [ ] [`invalid/string/bad-uni-esc-4.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/bad-uni-esc-4.toml)
- [ ] [`invalid/string/bad-uni-esc-5.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/bad-uni-esc-5.toml)
- [ ] [`invalid/string/bad-uni-esc-7.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/bad-uni-esc-7.toml)
- [ ] [`invalid/string/bad-uni-esc-6.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/bad-uni-esc-6.toml)
- [ ] [`invalid/string/basic-byte-escapes.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/basic-byte-escapes.toml)
- [ ] [`invalid/string/basic-multiline-out-of-range-unicode-escape-2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/basic-multiline-out-of-range-unicode-escape-2.toml)
- [ ] [`invalid/string/basic-multiline-out-of-range-unicode-escape-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/basic-multiline-out-of-range-unicode-escape-1.toml)
- [ ] [`invalid/string/basic-multiline-unknown-escape.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/basic-multiline-unknown-escape.toml)
- [ ] [`invalid/string/basic-out-of-range-unicode-escape-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/basic-out-of-range-unicode-escape-1.toml)
- [ ] [`invalid/string/basic-out-of-range-unicode-escape-2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/basic-out-of-range-unicode-escape-2.toml)
- [ ] [`invalid/string/basic-unknown-escape.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/basic-unknown-escape.toml)
- [ ] [`invalid/string/multiline-bad-escape-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/multiline-bad-escape-1.toml)
- [ ] [`invalid/string/multiline-bad-escape-2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/multiline-bad-escape-2.toml)
- [ ] [`invalid/string/multiline-bad-escape-4.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/multiline-bad-escape-4.toml)
- [ ] [`invalid/string/multiline-bad-escape-3.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/multiline-bad-escape-3.toml)
- [ ] [`invalid/string/multiline-escape-space-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/multiline-escape-space-1.toml)
- [ ] [`invalid/string/multiline-escape-space-2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/string/multiline-escape-space-2.toml)
- [ ] [`invalid/table/append-to-array-with-dotted-keys.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/table/append-to-array-with-dotted-keys.toml)
- [ ] [`invalid/table/duplicate-key-dotted-array.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/table/duplicate-key-dotted-array.toml)
- [ ] [`invalid/table/duplicate-key-dotted-table.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/table/duplicate-key-dotted-table.toml)
- [ ] [`invalid/table/append-with-dotted-keys-2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/table/append-with-dotted-keys-2.toml)
- [ ] [`invalid/table/array-implicit.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/table/array-implicit.toml)
- [ ] [`invalid/table/duplicate-table-array.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/table/duplicate-table-array.toml)
- [ ] [`invalid/table/duplicate-key-dotted-table2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/table/duplicate-key-dotted-table2.toml)
- [ ] [`invalid/table/append-with-dotted-keys-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/table/append-with-dotted-keys-1.toml)
- [ ] [`invalid/table/duplicate-key-table.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/table/duplicate-key-table.toml)
- [ ] [`invalid/table/duplicate-table-array2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/table/duplicate-table-array2.toml)
- [ ] [`invalid/table/duplicate.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/table/duplicate.toml)
- [ ] [`invalid/table/overwrite-bool-with-array.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/table/overwrite-bool-with-array.toml)
- [ ] [`invalid/table/overwrite-with-deep-table.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/table/overwrite-with-deep-table.toml)
- [ ] [`invalid/table/redefine-1.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/table/redefine-1.toml)
- [ ] [`invalid/table/redefine-2.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/table/redefine-2.toml)
- [ ] [`invalid/table/super-twice.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/table/super-twice.toml)
- [ ] [`invalid/table/overwrite-array-in-parent.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/table/overwrite-array-in-parent.toml)
- [ ] [`invalid/table/redefine-3.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/invalid/table/redefine-3.toml)
- [ ] [`valid/table/sub-empty.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/table/sub-empty.toml)
- [ ] [`valid/table/array-table-array.toml`](https://github.com/toml-lang/toml-test/blob/master/tests/valid/table/array-table-array.toml)

</details>

**Comment by zeenix** [comment]
This is so awesome!!! :+1: 

Some of the comments on #7 apply here as well. However, in this case I'd rather want to merge already before fixing all the issues since we can ignore them and this is already being run as part of the CI and will help avoid regressions.

**Comment by zeenix** [comment]
@CosmicHorrorDev I took the liberty of adding an emoji to your commit and the PR title so I can merge already. I hope you don't mind.

**Comment by zeenix** [comment]
> Failing tests

BTW, I gotta ask, how did you turn every item in the list into a link to the file? :thinking:

**Comment by CosmicHorrorDev** [comment]
I used a vim macro 😁 

Something along the lines of copy and paste the test path -> split the two sides where the left is the displayed text and the right is the URL -> move down a line and then finally have the macro run ~200 times

**Comment by CosmicHorrorDev** [comment]
Oh and I got the list of test paths just from removing all the ignore patterns and copying the list of failures from running the test suite

**Comment by zeenix** [comment]
> Oh and I got the list of test paths just from removing all the ignore patterns and copying the list of failures from running the test suite

That part I figured but thanks for sharing. :)

**Pull request merged**
